name = "Berettitland"
author = "Felix Cusson"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc927fcf0c5974fed06f7e8e07cd41e5721898ea0b1eeec69b855aa63584f827"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
