name = "Berettitland"
author = "Felix Cusson"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "969a80530c7544d80e2ba0bb15d9bd2341b3541db25dea40c5499b5c1fe9da8a"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
